sudo: required

services:
 - docker

before_install:
 - docker build -t bk20191210/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true bk20191210/react-test npm test

after_success:
 - docker build -t bk20191210/complex-client ./client
 - docker build -t bk20191210/complex-nginx ./nginx
 - docker build -t bk20191210/complex-server ./server
 - docker build -t bk20191210/complex-worker ./worker
 # Login to docker CLI
 - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
 # Take these images and push to docker hub
 - docker push bk20191210/complex-client
 - docker push bk20191210/complex-nginx
 - docker push bk20191210/complex-server
 - docker push bk20191210/complex-worker

